<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <h2 class="azul" style="text-align: center;">SUSTENTABILIDADE, INOVAÇÃO E TECNOLOGIA</h2>

            <p>
                Conhece as características do composto Carbet:
            </p>

            <br/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12" style="text-align: center;">

            <img src="/img/agentes.png" style="width: 160px; margin-right: 20px;" />
            <img src="/img/isolante.png" style="width: 160px; margin-right: 20px;" />
            <img src="/img/umidade.png" style="width: 160px; margin-right: 20px;" />
            <img src="/img/fogo.png" style="width: 160px;" />
        </div>
    </div>

    <br/>
    <br/>

    <div class="row-fluid">
        <div class="span12" style="text-align: center;">
            <img src="/img/produto.png" alt="Produto Carbet" />
        </div>
    </div>

    <br/>
</div>