<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <h2 class="azul" style="text-align: center;">SUSTENTABILIDADE, INOVAÇÃO E TECNOLOGIA</h2>

            <p>
                Em meados dos anos 70, com a crise do petróleo, gerou-se uma demanda global por métodos de 
                construção alternativos, que não utilizassem petróleo. Grande parte das construções europeias 
                necessitavam de isolamento térmico, e o material mais comum para tal fim era o isopor. 
                Quando este escasseou e encareceu, começaram a ser pesquisados materiais alternativos 
                para construção que tinham propriedades térmicas. Neste contexto foi concebido o Carbet®, 
                composto por fibra de celulose, cimento e aditivos. Os blocos Carbet apresentam resistência, 
                durabilidade e isolação térmica. 
            </p>

            <p>
                No ano de 1984 a mistura já havia sido desenvolvida e exaustivamente testada. 
            </p>

            <p>
                No ano de 1995 tal invento recebeu a medalha de ouro no 23º Salão 
                Internacional de Invenções em Genebra.
            </p>

            <p>
                Em 2003 identificou-se a oportunidade de utilizar os blocos Carbet no Brasil. 
                No ano de 2009, nasceu a empresa Carbet Brasil Tecnologia de Construção Ltda, 
                através da parceria de empresários que acreditaram e investiram no negócio.  
            </p>

            <p>
                Com as pesquisas brasileiras que a Carbet conduziu, foi formulada uma nova mistura, 
                com as mesmas características da mistura anterior, mas com a possibilidade de ser 
                moldada por prensagem, melhorando desta forma o processo de produção.
            </p>
            <br/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12" style="text-align: center;">

            <a href="#" id="linkVisao"><img src="/img/visao.png" style="width: 130px; margin-right: 20px;" /></a>
            <a href="#" id="linkMissao"><img src="/img/missao.png" style="width: 130px; margin-right: 20px;" /></a>
            <a href="#" id="linkValores"><img src="/img/valores.png" style="width: 130px;" /></a>
        </div>
    </div>

    <div class="row-fluid">
        <div id="visao" style="display: none;">
            <hr/>
            <h3>Visão</h3>
            <p>
                Ser reconhecida nacionalmente pela inovação, preocupação com recursos naturais, 
                pelo compromisso de aperfeiçoamento contínuo de seus produtos e com o 
                desenvolvimento sustentável e rentabilidade dos seus negócios.
            </p>
        </div>

        <div id="missao" style="display: none;">
            <hr/>
            <h3>Missão</h3>
            <p>
                Proporcionar segurança, conforto  e qualidade nas construções para todas 
                as classes sociais, utilizando tecnologias inovadoras, reduzindo impactos 
                ambientais e gerando resultados para seus investidores. 
            </p>
        </div>

        <div id="valores" style="display: none;">
            <hr/>
            <h3>Valores</h3>

            <ul>
                <li>Inovação;</li>
                <li>Sustentabilidade;</li>
                <li>Melhoria continua;</li>
                <li>Integridade;</li>
                <li>Respeito;</li>
                <li>Compromisso;</li>
                <li>Superação de resultados;</li> 

            </ul>
        </div>
    </div>

    <br/>
</div>

<script>
    $("#linkVisao").click(function() {
        $("#visao").hide();
        $("#missao").hide();
        $("#valores").hide();

        $("#visao").toggle("slow");
    });

    $("#linkMissao").click(function() {
        $("#visao").hide();
        $("#missao").hide();
        $("#valores").hide();

        $("#missao").toggle("slow");
    });

    $("#linkValores").click(function() {
        $("#visao").hide();
        $("#missao").hide();
        $("#valores").hide();

        $("#valores").toggle("slow");
    });
</script>