<div class="container">
    <div class="row-fluid">
        <div class="span12">
            
            <h2 class="azul">Franquia</h2>
            
            <p>
                A Carbet® Tecnologia de Construção Ltda, com objetivo de disponibilizar 
                os seus produtos para todo território nacional, esta utilizando 
                o sistema de franquias. 
            </p>

            <p>
                As franquias da Carbet apresentam um diferencial no segmento de franquias, 
                pois as unidades farão a produção e comercialização dos produtos, reduzindo 
                custos produtivos, aumentando a rentabilidade das unidades.  
            </p>

            <p>
                Seja um franqueado, preencha o formulário abaixo que entraremos em contato:  
            </p>

            <br/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12" style="text-align: center;">
            <a href="/seja-um-franqueado" id="linkFranquia"><img src="/img/franqueado.png" style="width: 180px;"/></a>
        </div>
    </div>
</div>

<br/>
<br/>
<br/>