<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <h2 class="azul" style="text-align: center;">SUSTENTABILIDADE, INOVAÇÃO E TECNOLOGIA</h2>

            <p>
                Como alternativa à cerâmica e ao concreto, que estimulam os passivos ambientais 
                devidos à extração do barro, da areia e da brita, o bloco Carbet® utiliza 
                como matéria-prima a fibra de celulose, obtida a partir do papel, 
                evitando que tal material seja queimado e libere carbono para a atmosfera - ou seja, 
                a matéria prima dos blocos Carbet seria depositada em lixões - dando um novo uso para 
                um material que foi descartado. É um novo processo de reciclagem para a celulose, 
                agora incorporando às construções, evitando poluir o meio-ambiente. 
            </p>

            <p>
                Os blocos Carbet® apresentam características mecânicas equivalentes e 
                características físicas que superam às do concreto. Mesmo tendo a mesma
                resistência dos blocos de concreto, que é superior à dos blocos cerâmicos, 
                os blocos Carbet® são mais leves, reduzindo custos com estrutura da obra, 
                acabamento de paredes, condicionamento térmicos dos ambientes, entre outros.
            </p>

            <p>
                Os blocos Carbet® atendem as exigências da Norma Brasileira Regulamentadora 
                (NBR) 15575, que institui parâmetros técnicos para vários requisitos importantes 
                de uma edificação e tem como características estabelecer as responsabilidades de 
                cada um dos envolvidos: construtores, incorporadores, projetistas, fabricantes de
                materiais, administradores condominiais e os próprios usuários.
            </p>

            <br/>
        </div>
    </div>

    <div class="row-fluid navegacao">
        <div class="span12" style="text-align: center;">
            <a href="#caracteristicas" id="linkCaracteristicas"><img src="/img/caracteristicas.png" style="width: 160px; margin-right: 20px;" /></a>
            <a href="#sustentabilidade" id="linkSustentabilidade"><img src="/img/sustentabilidade.png" style="width: 160px; margin-right: 20px;" /></a>
            <a href="#vantagens" id="linkVantagens"><img src="/img/vantagens.png" style="width: 160px;" /></a>
        </div>
    </div>

    <div class="row-fluid">
        <div id="caracteristicas" style="display: none;">
            <br/>
            <hr/>

            <h3>Características</h3>
            <br/>

            <div class="row-fluid">
                <div class="span12" style="text-align: center;">

                    <a href="javascript:void(0);" data-toggle="modal" data-target="#agentes">
                        <img src="/img/agentes.png" style="width: 160px; margin-right: 20px;" />
                    </a>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#isolante">
                        <img src="/img/isolante.png" style="width: 160px; margin-right: 20px;" />
                    </a>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#umidade">
                        <img src="/img/umidade.png" style="width: 160px; margin-right: 20px;" />
                    </a>
                    <a href="javascript:void(0);" data-toggle="modal" data-target="#fogo">
                        <img src="/img/fogo.png" style="width: 160px;" />
                    </a>
                </div>
            </div>

            <br/>
            <br/>

            <div class="row-fluid">
                <div class="span12" style="text-align: center;">
                    <img src="/img/produto.png" alt="Produto Carbet" />
                </div>
            </div>
        </div>

        <div id="sustentabilidade" style="display: none;">
            <br/>
            <hr/>
            <h3>Sustentabilidade</h3>
            <ul>
                <li>
                    Meio ambiente preservado, uma vez que não utiliza argila, areia e brita. 
                    Sua fabricação não estimula os danos ambientais como na extração das matérias 
                    primas dos blocos cerâmicos e de concreto;
                </li>
                <li>
                    O processo produtivo não libera de nenhuma maneira contaminação no solo, 
                    fontes hídricas ou na atmosfera;
                </li>
                <li>A matéria prima principal é a fibra de celulose, obtida de descarte de papel;</li>
                <li>
                    Os blocos Carbet® fixam carbono nas construções gerando economia de energia 
                    pela redução das perdas de condicionamento térmico para o ambiente.
                </li>
            </ul>
        </div>

        <div id="vantagens" style="display: none;">
            <br/>
            <hr/>
            <h3>Vantagens</h3>

            <ul>
                <li>
                    Agilidade na construção: por serem de base cimentícia os blocos Carbet® dispensam chapisco; 
                    por terem as faces lisas e arestas perfeitas, pode-se optar por não aplicar as camadas de emboço 
                    e reboco e realizar a pintura ou texturização diretamente, ou então aplicar massa corrida.
                </li>
                <li>
                    Flexibilidade: pode ser trabalhado com as mesmas ferramentas utilizados para com a madeira, 
                    sendo: serrado, furado, lixado, plainado, cortado, desbastado, esculpido, dentre outros. 
                    No caso de parafusos, ganchos e pítons, não é necessário utilização de buchas, 
                    basta um pré-furo, como na madeira. 
                </li>
                <li>
                    Blocos maiores: por possuir baixo peso específico, faz-se possível usar maior modulação. 
                    Por serem fabricados em grandes dimensões, proporcionam maior velocidade de assentamento, 
                    consumindo menos argamassa e consequentemente diminuído o tempo de construção e seu custo.
                </li>
            </ul>
        </div>
    </div>

    <br/>
</div>

<script>
    /*jQuery("document").ready(function($) {
     var nav = $('.navegacao');
     $(window).scroll(function() {
     if ($(this).scrollTop() > 400) {
     nav.addClass("f-nav");
     } else {
     nav.removeClass("f-nav");
     }
     });
     });*/

    $("#linkCaracteristicas").click(function() {
        $("#caracteristicas").hide();
        $("#sustentabilidade").hide();
        $("#vantagens").hide();

        $("#caracteristicas").toggle("slow");
    });

    $("#linkSustentabilidade").click(function() {
        $("#caracteristicas").hide();
        $("#sustentabilidade").hide();
        $("#vantagens").hide();

        $("#sustentabilidade").toggle("slow");
    });

    $("#linkVantagens").click(function() {
        $("#caracteristicas").hide();
        $("#sustentabilidade").hide();
        $("#vantagens").hide();

        $("#vantagens").toggle("slow");
    });

</script>

<!-- Modal Agentes Biológicos -->
<div class="modal fade" id="agentes" tabindex="0" role="dialog" aria-labelledby="labelAgentes" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="labelAgentes">Proteção contra agentes biológicos</h4>
            </div>
            <div class="modal-body">
                <div class="row-fluid" style="text-align: center;">
                    <img src="/img/agentes.png" style="width: 130px;"/>
                </div>
                <hr/>
                <p>
                    Pela aditivação que recebe, o bloco Carbet® não é passível de sofrer ataques de fungos, 
                    bolores, cupins, brocas, vermes e qualquer outro agente biológico. 
                </p>
            </div>
        </div>
    </div>
</div>


<!-- Modal Isolante Térmico -->
<div class="modal fade" id="isolante" tabindex="1" role="dialog" aria-labelledby="labelIsolante" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="labelIsolante">Isolante térmico</h4>
            </div>
            <div class="modal-body">
                <div class="row-fluid" style="text-align: center;">
                    <img src="/img/isolante.png" style="width: 130px;"/>
                </div>
                <hr/>
                <p>
                    O composto Carbet® é mais isolante que o isopor e quando usado 
                    no formato de blocos confere excelente isolamento, inclusive para 
                    locais de necessidades mais intensas. Isto reflete diretamente na economia 
                    de condicionamento de ar para equilíbrio da temperatura do ambiente. 
                </p>
            </div>
        </div>
    </div>
</div>

<!-- Modal Umidade -->
<div class="modal fade" id="umidade" tabindex="2" role="dialog" aria-labelledby="labelUmidade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="labelUmidade">Equilibra a umidade do ambiente</h4>
            </div>
            <div class="modal-body">
                <div class="row-fluid" style="text-align: center;">
                    <img src="/img/umidade.png" style="width: 130px;"/>
                </div>
                <hr/>
                <p>
                    O composto Carbet® promove a criação de um micro-clima estável dentro
                    da edificação, estabilizando a temperatura e a umidade do ar. As paredes 
                    absorvem umidade quando o ambiente está muito úmido e libera quando a
                    umidade relativa do ar esta muito baixa, promovendo um ambiente mais 
                    saudável e evitando doenças respiratórias. 
                </p>
            </div>
        </div>
    </div>
</div>

<!-- Modal Fogo -->
<div class="modal fade" id="fogo" tabindex="3" role="dialog" aria-labelledby="labelFogo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="labelFogo">Proteção contra fogo</h4>
            </div>
            <div class="modal-body">
                <div class="row-fluid" style="text-align: center;">
                    <img src="/img/fogo.png" style="width: 130px;"/>
                </div>
                <hr/>
                <p>
                    Os blocos são incombustíveis e pelas suas características térmicas, ele protege para que as altas 
                    temperaturas geradas em incêndios não alcancem a outra face da alvenaria, sendo um dos materiais
                    mais adequados para alvenarias que devam proteger contra o fogo. 
                </p>
            </div>
        </div>
    </div>
</div>