<div class="container">
    <div class="row-fluid">
        <div class="span12">

            <h2 class="azul">SEJA UM FRANQUEADO</h2>
            <p>
                Preencha os dados abaixo que entraremos em contato com você: 
            </p>

            <br/>

            <div class="row-fluid">

                <div class="span8">
                    <form method="post">
                        <div class="controls-row">
                            <div class="control-group">
                                <label for="nome" class="control-label">Nome Completo:</label>
                                <div class="controls">
                                    <input type="text" id="nome" name="nome" class="input-xlarge"/>
                                </div>                
                            </div>

                            <div class="control-group offset1">
                                <label for="profissao" class="control-label">Profissão:</label>
                                <div class="controls">
                                    <input type="text" id="profissao" name="profissao" class="input-large"/>
                                </div>                
                            </div>  
                        </div>

                        <div class="controls-row">
                            <div class="control-group">
                                <label for="dtNascimento" class="control-label">Data de nascimento:</label>
                                <div class="controls">
                                    <input type="text" id="dtNascimento" name="dtNascimento" class="input-xlarge"/>
                                </div>                
                            </div>  

                            <div class="control-group offset1">
                                <label for="email" class="control-label">E-mail:</label>
                                <div class="controls">
                                    <input type="text" id="email" name="email" class="input"/>
                                </div>                
                            </div>      
                        </div>

                        <div class="controls-row">
                            <div class="control-group">
                                <label for="foneFixo" class="control-label">Telefone Fixo:</label>
                                <div class="controls">
                                    <input type="text" id="foneFixo" name="foneFixo" class="input-xlarge"/>
                                </div>                
                            </div>  

                            <div class="control-group offset1">
                                <label for="foneCelular" class="control-label">Telefone Celular:</label>
                                <div class="controls">
                                    <input type="text" id="foneCelular" name="foneCelular" class="input"/>
                                </div>                
                            </div>      
                        </div>

                        <div class="controls-row">
                            <div class="control-group">
                                <label for="cidade" class="control-label">Cidade:</label>
                                <div class="controls">
                                    <input type="text" id="cidade" name="cidade" class="input-xlarge"/>
                                </div>                
                            </div>  

                            <div class="control-group offset1">
                                <label for="uf" class="control-label">Estado:</label>
                                <div class="controls">
                                    <input type="text" id="uf" name="uf" class="input"/>
                                </div>                
                            </div>      
                        </div>

                        <input type="submit" id="submitbutton" class="btn btn-primary" value="Enviar">  
                    </form>
                </div>
                
                <div class="span4">
                    <img src="/img/brasil.png" />
                </div>
            </div>

            <h4>CARBET = FUTURO + SUSTENTABILIDADE</h4>
            <br/>
        </div>
    </div>
</div>