<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Carbet</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Bootstrap -->
        <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/lib/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">

        <!-- font-awesome -->
        <link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">

        <!-- Style -->
        <link href="/css/style.css" rel="stylesheet" media="screen">

        <!-- scripts -->
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/modernizr.min.js"></script>
        <script type="text/javascript" src="/js/jquery.price.js"></script>
        <script type="text/javascript" src="/js/jquery.inputmask.js"></script>
        <!--[if lt IE 9]>
        <script type="text/javascript" src="/js/html5.js"></script>
        <![endif]-->
        <script type="text/javascript" src="/lib/validation/jquery.validate.min.js"></script>
        <script type="text/javascript" src="/lib/validation/localization/messages_ptbr.js"></script>
        <script type="text/javascript" src="/lib/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>