<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Carbet Tecnologia de Construção</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Bootstrap -->
        <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/lib/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">

        <!-- font-awesome -->
        <link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">

        <!-- Style -->
        <link href="/css/style.css" rel="stylesheet" media="screen">

        <!-- scripts -->
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/modernizr.min.js"></script>
        <script type="text/javascript" src="/js/jquery.price.js"></script>
        <script type="text/javascript" src="/js/jquery.inputmask.js"></script>
        <!--[if lt IE 9]>
        <script type="text/javascript" src="/js/html5.js"></script>
        <![endif]-->
        <script type="text/javascript" src="/lib/validation/jquery.validate.min.js"></script>
        <script type="text/javascript" src="/lib/validation/localization/messages_ptbr.js"></script>
        <script type="text/javascript" src="/lib/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
    </head>
    <body>
        <div id="header">
            <div style="height: 50px; background: #2185e3;"></div>
            <div style="height: 5px;"></div>
            <div style="height: 5px; background: #2185e3;"></div>

            <div class="container">
                <div class="row-fluid">
                    <div class="span4">
                        <h1 id="logo">
                            <a href="/"><img src="/img/logo.png" alt="Carbet Tecnologia em Construção" /></a>
                        </h1>
                    </div>

                    <div class="span8 visible-desktop" id="nav-container">

                        <div id="nav">
                            <ul>
                                <li><a href="/home">Home</a></li>
                                <li>|</li>
                                <li><a href="/empresa">Empresa</a></li>
                                <li>|</li>
                                <li><a href="/produto">Produto</a></li>
                                <li>|</li>
                                <li><a href="/franquia">Franquia</a></li>
                                <li>|</li>
                                <li><a href="/metodos">Métodos</a></li>
                                <li>|</li>
                                <li><a href="/contato">Contato</a></li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>

        <div id="footer">
            <div style="height: 5px; background: #2185e3;"></div>
            <div style="height: 5px;"></div>
            <div style="min-height: 70px; background: #2185e3;">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span6 address">
                            <p>
                                Av. Cristovão Colombo, 4127 - Pq. Industrial - 86990-000 - Marialva/PR
                            </p>
                            <p>
                                Copyright &copy; Carbet. 2013 - Todos os direitos reservados
                            </p>
                        </div>

                        <div class="span6 fone">
                            <div class="right">
                                <img src="/img/fone.png" alt="fone" style="margin-top: 2px; margin-right: 15px;"/>
                                <h3>
                                    (44)3232-0101
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>